import burger from '../images/burger.jpg';
import pizza from '../images/pizza.jpg';
import cola from '../images/cola.jpg';
import icecream from '../images/icecream.jpg';
import frenchfries from '../images/frenchfries.jpg';

export const goods = [
  {
    id: 'a123d',
    name: 'Big Big Burger',
    photo: burger,
    price: 100,
    count: 1,
    totalPrice: 100,
  },
  {
    id: 'a234d',
    name: 'Big Big Burger',
    photo: burger,
    price: 80,
    count: 1,
    totalPrice: 80,
  },
  {
    id: 'a345d',
    name: 'Big Big Burger',
    photo: burger,
    price: 90,
    count: 1,
    totalPrice: 90,
  },
  {
    id: 'a456d',
    name: 'Big Big Burger',
    photo: burger,
    price: 75,
    count: 1,
    totalPrice: 75,
  },
  {
    id: 'a567d',
    name: 'Big Big Burger',
    photo: burger,
    price: 65,
    count: 1,
    totalPrice: 65,
  },
  {
    id: 'a678d',
    name: 'Big Big Burger',
    photo: burger,
    price: 25,
    count: 1,
    totalPrice: 25,
  },
  {
    id: 'a789d',
    name: 'Big Big Burger',
    photo: burger,
    price: 95,
    count: 1,
    totalPrice: 95,
  },
  {
    id: 'b123c',
    name: 'Big Big Pizza',
    photo: pizza,
    price: 100,
    count: 1,
    totalPrice: 100,
  },
  {
    id: 'b234c',
    name: 'Big Big Pizza',
    photo: pizza,
    price: 80,
    count: 1,
    totalPrice: 80,
  },
  {
    id: 'b345c',
    name: 'Big Big Pizza',
    photo: pizza,
    price: 90,
    count: 1,
    totalPrice: 90,
  },
  {
    id: 'b456c',
    name: 'Big Big Pizza',
    photo: pizza,
    price: 75,
    count: 1,
    totalPrice: 75,
  },
  {
    id: 'b567c',
    name: 'Big Big Pizza',
    photo: pizza,
    price: 65,
    count: 1,
    totalPrice: 65,
  },
  {
    id: 'b6c78',
    name: 'Big Big Pizza',
    photo: pizza,
    price: 25,
    count: 1,
    totalPrice: 25,
  },
  {
    id: 'b789c',
    name: 'Big Big Pizza',
    photo: pizza,
    price: 95,
    count: 1,
    totalPrice: 95,
  },
  {
    id: 'b890c',
    name: 'Big Big Pizza',
    photo: pizza,
    price: 95,
    count: 1,
    totalPrice: 95,
  },
  {
    id: 'h231p',
    name: 'Big Big Cola',
    photo: cola,
    price: 100,
    count: 1,
    totalPrice: 100,
  },
  {
    id: 'h234p',
    name: 'Big Big Cola',
    photo: cola,
    price: 80,
    count: 1,
    totalPrice: 80,
  },
  {
    id: 'h345p',
    name: 'Big Big Cola',
    photo: cola,
    price: 90,
    count: 1,
    totalPrice: 90,
  },
  {
    id: 'h456p',
    name: 'Big Big Cola',
    photo: cola,
    price: 75,
    count: 1,
    totalPrice: 75,
  },
  {
    id: 'h567p',
    name: 'Big Big Cola',
    photo: cola,
    price: 65,
    count: 1,
    totalPrice: 65,
  },
  {
    id: 'h678p',
    name: 'Big Big Cola',
    photo: cola,
    price: 25,
    count: 1,
    totalPrice: 25,
  },
  {
    id: 'h789p',
    name: 'Big Big Cola',
    photo: cola,
    price: 95,
    count: 1,
    totalPrice: 95,
  },
  {
    id: 'h890p',
    name: 'Big Big Cola',
    photo: cola,
    price: 95,
    count: 1,
    totalPrice: 95,
  },
  {
    id: 'k123m',
    name: 'Big Ice Cream',
    photo: icecream,
    price: 100,
    count: 1,
    totalPrice: 100,
  },
  {
    id: 'k234m',
    name: 'Big Ice Cream',
    photo: icecream,
    price: 80,
    count: 1,
    totalPrice: 80,
  },
  {
    id: 'k345m',
    name: 'Big Ice Cream',
    photo: icecream,
    price: 90,
    count: 1,
    totalPrice: 90,
  },
  {
    id: 'k456m',
    name: 'Big Ice Cream',
    photo: icecream,
    price: 75,
    count: 1,
    totalPrice: 75,
  },
  {
    id: 'k567m',
    name: 'Big Ice Cream',
    photo: icecream,
    price: 65,
    count: 1,
    totalPrice: 65,
  },
  {
    id: 'k678m',
    name: 'Big Ice Cream',
    photo: icecream,
    price: 25,
    count: 1,
    totalPrice: 25,
  },
  {
    id: 'k789m',
    name: 'Big Ice Cream',
    photo: icecream,
    price: 95,
    count: 1,
    totalPrice: 95,
  },
  {
    id: 'r123z',
    name: 'French Fries',
    photo: frenchfries,
    price: 100,
    count: 1,
    totalPrice: 100,
  },
  {
    id: 'r234z',
    name: 'French Fries',
    photo: frenchfries,
    price: 80,
    count: 1,
    totalPrice: 80,
  },
  {
    id: 'r345z',
    name: 'French Fries',
    photo: frenchfries,
    price: 90,
    count: 1,
    totalPrice: 90,
  },
  {
    id: 'r456z',
    name: 'French Fries',
    photo: frenchfries,
    price: 75,
    count: 1,
    totalPrice: 75,
  },
  {
    id: 'r567z',
    name: 'French Fries',
    photo: frenchfries,
    price: 65,
    count: 1,
    totalPrice: 65,
  },
  {
    id: 'r678z',
    name: 'French Fries',
    photo: frenchfries,
    price: 25,
    count: 1,
    totalPrice: 25,
  },
  {
    id: 'r789z',
    name: 'French Fries',
    photo: frenchfries,
    price: 95,
    count: 1,
    totalPrice: 95,
  },
];

export const getProductById = elId => {
  return goods.find(el => el.id === elId);
};
