import icecream from '../images/icecream.jpg';

export const goods = [
  {
    id: 'k123m',
    name: 'Big Ice Cream',
    photo: icecream,
    price: 100,
    count: 1,
    totalPrice: 100,
  },
  {
    id: 'k234m',
    name: 'Big Ice Cream',
    photo: icecream,
    price: 80,
    count: 1,
    totalPrice: 80,
  },
  {
    id: 'k345m',
    name: 'Big Ice Cream',
    photo: icecream,
    price: 90,
    count: 1,
    totalPrice: 90,
  },
  {
    id: 'k456m',
    name: 'Big Ice Cream',
    photo: icecream,
    price: 75,
    count: 1,
    totalPrice: 75,
  },
  {
    id: 'k567m',
    name: 'Big Ice Cream',
    photo: icecream,
    price: 65,
    count: 1,
    totalPrice: 65,
  },
  {
    id: 'k678m',
    name: 'Big Ice Cream',
    photo: icecream,
    price: 25,
    count: 1,
    totalPrice: 25,
  },
  {
    id: 'k789m',
    name: 'Big Ice Cream',
    photo: icecream,
    price: 95,
    count: 1,
    totalPrice: 95,
  },
];
