import burger from '../images/burger.jpg';

export const goods = [
  {
    id: 'a123d',
    name: 'Big Big Burger',
    photo: burger,
    price: 100,
    count: 1,
    totalPrice: 100,
  },
  {
    id: 'a234d',
    name: 'Big Big Burger',
    photo: burger,
    price: 80,
    count: 1,
    totalPrice: 80,
  },
  {
    id: 'a345d',
    name: 'Big Big Burger',
    photo: burger,
    price: 90,
    count: 1,
    totalPrice: 90,
  },
  {
    id: 'a456d',
    name: 'Big Big Burger',
    photo: burger,
    price: 75,
    count: 1,
    totalPrice: 75,
  },
  {
    id: 'a567d',
    name: 'Big Big Burger',
    photo: burger,
    price: 65,
    count: 1,
    totalPrice: 65,
  },
  {
    id: 'a678d',
    name: 'Big Big Burger',
    photo: burger,
    price: 25,
    count: 1,
    totalPrice: 25,
  },
  {
    id: 'a789d',
    name: 'Big Big Burger',
    photo: burger,
    price: 95,
    count: 1,
    totalPrice: 95,
  },
];
